version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "db-migrate up && npm start"
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del host al puerto 3000 del contenedor
    volumes:
      - ./images:/app/images
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
